services:
  fastapi-books-app:
    image: ghcr.io/kntuli/fastapi-book-project:${DOCKER_TAG}  # Replace with your image path
    restart: unless-stopped
    env_file:
      - .env 
    # networks:
    #   - app_network

  nginx:
    restart: unless-stopped
    image: nginx:alpine
    container_name: fastapi_books_nginx
    ports:
      - "8083:8083"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi-books-app
    # networks:
    #   - app_network

  # networks:
  #   app_network:
  #   driver: bridge   