services:
  fastapi-books-app:
    build: .
    ports:
      - "8084:8084"
    container_name: fastapi_books_app
    restart: unless-stopped
    # networks:
    #   - app_network

  nginx:
    restart: unless-stopped
    image: nginx:alpine
    container_name: fastapi_books_nginx
    ports:
      - "8083:8083"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi-books-app
    # networks:
    #   - app_network

  # networks:
  #   app_network:
  #   driver: bridge   