name: CI & CD Pipeline

on:
  push:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.actor}}/fastapi-book-project:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}

    steps:
    - uses: actions/checkout@v4
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +%s)"  
    - name: Build the Docker image   
      run: docker build . --file Dockerfile  --tag ghcr.io/kntuli/fastapi-book-project:${{ steps.date.outputs.date }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    - name: Push the Docker image to the GitHub registry
      run: docker push ghcr.io/kntuli/fastapi-book-project:${{ steps.date.outputs.date }}

  
  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # - name: Add remote server to known_hosts
      #   run: |
      #               ssh-keyscan root@192.168.101.173 >> ~/.ssh/known_hosts    # Replace user@remote_server

      - name: Deploy to server
        run: |
          ssh root@192.168.101.173 << 'EOF'                         # Replace user@remote_server
            cd /var/www/fastapi-book-project           # Replace with your Docker Compose folder
            sed -i 's/^DOCKER_TAG=.*/DOCKER_TAG=${{ needs.publish.outputs.date }}/' .env
            docker compose up -d
          EOF 

