name: CI Pipeline

on:
  push:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.actor}}/fastapi-book-project:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u kntuli --password-stdin
    - name: Build and Publish
      run: |
        docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  
  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
    - name: Multiple commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UBUNTU_HOST}}
        username: ${{ secrets.UBUNTU_USER}}
        key: ${{ secrets.UBUNTU_KEY }}
        port: 22
        script: |
          whoami
          ls -al
    - name: connect and pull
      run: ssh root@192.168.101.173 "cd /var/www/fastapi-book-project && docker-compose pull && docker-compose up -d && exit"
    - name: cleanup
      run: rm -rf ~/root/ssh
